sudo: false
cache:
  directories:
    - node_modules
git:
  depth: 1
language: node_js
node_js:
  - "2.4"
  - "stable"

before_install:
  - npm install -g grunt-cli

script: grunt travis

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7a0fcab3f65f36d44ac5
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false